# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5ec42d89d013ff2e19285463aed3d12c489fa3932303d87cba373d68bf240771d941d19e618b0b764fe7d79605c75c4f74e63d3cb4eadf1dce10b47fd2b7021

test:
  secret_key_base: 4ab3a3d153b5aff84ca6ceb083cfe7169f64907971df70ffc649e9e5fadabf47808931f3bb5c417cb86b54f5932fae231e0318d1f169889bab3389f589793c32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
